service:
    access_limiting_service:
        arguments: [@request, @response, @individual_recognizer, @redis]
        events: ['route.dispatch.before']
        class: \VJ\EventListener\AccessLimitingService

    vj_redirection_service:
        arguments: [@request, @response, %canonical, %security.enforce_https]
        events: ['route.dispatch.before']
        class: \VJ\EventListener\VJRedirectionService

    https_redirection_service:
        arguments: [@request, @response, %canonical, %security.enforce_https]
        events: ['route.dispatch.before']
        class: \VJ\EventListener\HttpsRedirectionService

    rememberme_login_service:
        arguments: [@user_manager]
        events: ['route.dispatch.before']
        class: \VJ\EventListener\RememberMeLoginService

    csrf_checking_service:
        arguments: [@request, @user_session]
        events: ['route.dispatch']
        class: \VJ\EventListener\CsrfTokenCheckingService

    login_log_service:
        arguments: [@request]
        events: ['user.login.succeeded', 'user.login.failed.wrong_password']
        class: \VJ\EventListener\LoginLogService

    vj2_credential_upgrade_service:
        arguments: [@user_credential]
        events: ['user.login.succeeded']
        class: \VJ\EventListener\VJCredentialUpgradeService

    domain_service:
        arguments: [@domain_manager]
        events: ['user.created']
        class: \VJ\EventListener\DomainService

    individual_recognizer:
        arguments: [@request, @user_session]
        class: \VJ\Security\IndividualRecognizer

    keyword_filter:
        arguments: [@redis]
        class: \VJ\Security\KeywordFilter

    token_manager:
        class: \VJ\Security\TokenManager

    message_signer:
        arguments: ['sha256', %security.secret]
        class: \VJ\Security\MessageSigner

    user_session:
        arguments: [@session_storage]
        class: \VJ\User\UserSession

    domain_manager:
        arguments: [@user_session, @request]
        class: \VJ\User\DomainManager

    password_encoder:
        class: \VJ\User\PasswordEncoder

    user_credential:
        arguments: [@password_encoder]
        class: \VJ\User\UserCredential

    user_manager:
        arguments: [@user_session, @request, @response, @user_credential]
        class: \VJ\User\UserManager

    bgservice_mailing_provider:
        class: \VJ\Mail\BgServiceMailingProvider

    mail_sender:
        arguments: [@bgservice_mailing_provider]
        class: \VJ\Mail\Sender
